### ISSUE TITLE
how to hide a table column in boomi flow

### ISSUE THREAD

**Issue by vishnusangepu** [vishnusangepu/vishnu#1]
i want to hide a table column in a boomi flow using toggle button. the table values coming from salesforce service would you please help me to solve this .when i give the page condition the whole table is hiding. but i want to hide only one column data. in this we need any html/css to solve this? if we solve with the html/css please send me the script. thank you.i tried with different scenarios but it's not working for me. 
@ccappetta
@tillo13
@MatthewNorton
@DrewErie
@steve-manywho
@williamjeccles
@jonjomckay

**Comment by ccappetta** [comment]
@vishnusangepu that could probably be achieved with a custom component, but I don't have great line of sight to how it would be coded.

Personally I'd probably tackle this by just having two tables on the page. One with the column, one without the column. Then a page condition to basically say "if this toggle is true, show one table and hide the other." It's a pretty quick configuration and doesn't require any custom code.

Does that make sense?
